# Generated by Django 5.0.6 on 2024-06-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa instytucji')),
                ('description', models.TextField(verbose_name='Opis')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=1, verbose_name='Typ')),
                ('categories', models.ManyToManyField(to='charity_app.category', verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Liczba worków')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='Godzina odbioru')),
                ('pick_up_comment', models.TextField(blank=True, verbose_name='Komentarz do odbioru')),
                ('categories', models.ManyToManyField(to='charity_app.category', verbose_name='Kategorie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity_app.institution', verbose_name='Instytucja')),
            ],
        ),
    ]
